Vagrant.configure("2") do |config|
  config.vm.box = "box"

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "basic/cookbooks"
    chef.run_list = ["recipe[foo]"]
  end

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "basic-roles/cookbooks"
    chef.roles_path = "basic-roles/roles"
    chef.run_list = ["role[foo]"]
  end
end
