# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

sudo: false
language: ruby
rvm:
    - 2.4.6
    - 2.5.3
    - 2.6.5
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script: bundle exec rspec
