Vagrant.configure("2") do |config|
  config.vm.box = "box"

  config.vm.synced_folder ".", "/vagrant-smb", type: "smb", smb_username: ENV["SMB_USERNAME"], smb_password: ENV["SMB_PASSWORD"]
  config.vm.synced_folder ".", "/foo", type: "smb", disabled: true
  # Guest should persist mounts after reboot
  config.vm.provision "shell", inline: "echo goodbye", reboot: true
end
