Vagrant.configure("2") do |config|
  config.vm.box = "box"

  config.vm.disk :dvd, name: "dvd1", file: "./example1.iso"
  config.vm.disk :dvd, name: "dvd2", file: "./example2.iso"
  config.vm.disk :dvd, name: "dvd3", file: "./example3.iso"
  config.vm.disk :dvd, name: "dvd4", file: "./example4.iso"
end
