Vagrant.configure("2") do |config|
  config.vm.box = "box"

  config.vm.disk :dvd, name: "dvd1", file: "./example.iso"
  config.vm.disk :dvd, name: "dvd2", file: "./example.iso"
  config.vm.disk :dvd, name: "dvd3", file: "./example.iso"
  config.vm.disk :dvd, name: "dvd4", file: "./example.iso"
end
