Vagrant.configure("2") do |config|
  config.vm.box = "box"

  config.vm.synced_folder ".", "/vagrant-nfs", type: "nfs"
  config.vm.synced_folder ".", "/foo", type: "nfs", disabled: true
  config.vm.network "private_network", ip: "192.168.33.10"
end
